apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fmvs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fmvs
    app.kubernetes.io/part-of: my-app-node2
  name: devfile-sample-fmvs
  namespace: ktsao-tenant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fmvs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fmvs
    spec:
      containers:
      - env:
        - name: env
          value: var
        image: nodejs-image:latest
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 3005
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 12m
            memory: 52Mi
status: {}
