apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fmvs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fmvs
    app.kubernetes.io/part-of: my-app-node2
  name: devfile-sample-fmvs
  namespace: ktsao-tenant
spec:
  ports:
  - port: 3005
    targetPort: 3005
  selector:
    app.kubernetes.io/instance: devfile-sample-fmvs
status:
  loadBalancer: {}
